<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import type { FieldErrors } from "@/api/types";
import { reasonKey } from "@/lib/formErrors";
import { formatMoney, formatNumber } from "../format";
import type { AdvanceLineDraft } from "../lines";
import type { VatMode } from "../types";

/** A deducted advance: generated by settlement, read-only, can only be removed. */
const props = defineProps<{
  line: AdvanceLineDraft;
  index: number;
  currency: string;
  errors: FieldErrors;
  /** Formatted live base, when known; else the stored one. */
  base: string | null;
  vatMode: VatMode;
  /** The settled proforma: an advance line referencing it is the non-payer form, valid in any mode. */
  relatedDocumentId: string | null;
}>();
const emit = defineEmits<{ remove: [] }>();

const { t, locale } = useI18n();
const money = (v: string) => formatMoney(v, props.currency, locale.value);
/** A DDPP deduction (not the non-payer proforma form) is `invalid` outside standard VAT. */
const errorText = computed(() => {
  const reason = props.errors.advanceDocumentId;
  if (!reason) return null;
  const isDdpp = props.line.advanceDocumentId !== props.relatedDocumentId;
  return reason === "invalid" && isDdpp && props.vatMode !== "standard" ? t("documents.line.advanceNeedsStandard") : t(reasonKey(reason));
});
</script>

<template>
  <li class="space-y-2 rounded-md border border-dashed border-gray-300 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-800/40" :data-test="`line-${index}`">
    <div class="flex items-center gap-2">
      <span class="font-mono text-sm font-semibold" data-test="line-position">{{ index + 1 }}.</span>
      <span class="badge !bg-amber-100 !text-amber-800 dark:!bg-amber-900/50 dark:!text-amber-300">{{ t("documents.line.kinds.advance") }}</span>
      <span class="ml-auto text-sm tabular-nums" data-test="line-base">{{ base ?? (line.base ? money(line.base) : "") }}</span>
      <button type="button" class="btn btn-sm btn-danger" :aria-label="t('documents.line.remove', { n: index + 1 })" data-test="remove-line" @click="emit('remove')">✕</button>
    </div>
    <p class="text-sm">{{ line.description || t("documents.line.advancePending") }}</p>
    <table v-if="line.recap.length" class="table max-w-md text-xs">
      <thead>
        <tr>
          <th>{{ t("documents.totals.rate") }}</th>
          <th class="text-right">{{ t("documents.totals.base") }}</th>
          <th class="text-right">{{ t("documents.totals.vat") }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in line.recap" :key="r.vatRate" data-test="advance-recap-row">
          <td>{{ formatNumber(r.vatRate, locale, 2) }} %</td>
          <td class="text-right tabular-nums">{{ money(r.base) }}</td>
          <td class="text-right tabular-nums">{{ money(r.vat) }}</td>
        </tr>
      </tbody>
    </table>
    <p v-if="errorText" class="text-xs text-red-600 dark:text-red-400" data-test="field-error">{{ errorText }}</p>
  </li>
</template>
